webrtc: yes
webrtcAddress: :8889
webrtcICEHostNAT1To1IPs:
  - "18.141.183.26"

webrtcICEUDPMuxAddress: :8189

webrtcICEServers2:
  - url: stun:stun.l.google.com:19302

paths:
  all:
    source: publisher